### ISSUE TITLE
[Issue]: Build - Dependencies check: DLPack check missing

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/rocPyDecode#101]
### Problem Description

Building the rocPyDecode requires DLPack dev install and the build process has to find package DLPack and link libraries.

### Operating System

Ubuntu

### CPU

ALL

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.2.0

**Comment by essamROCm** [comment]
This is supposed to be achieved already via using the rocPyDecode-requirements.py script prior to building the rocPyDecode.

Any more details of what or how it is happening?

**Comment by kiritigowda** [comment]
@essamROCm we use the DLPack headers in the c++ code. We need to check the package install using finding package module to verify install and throw appropriate messages.

**Comment by essamROCm** [comment]
> @essamROCm we use the DLPack headers in the c++ code. We need to check the package install using finding package module to verify install and throw appropriate messages.

@kiritigowda 
That is doable, installing the dlpack as a package separately (done in rocPyDecode-requirements.py line 143 and 171) then checking inside cmake (which I am adding right now) which actually finds the package, but it doesn't know where the H files are, in compared to the pybind11 where it finds the package and the H file location.

We don't really need the cmake to find the H location of the dlpack, because it is installed currently as **-dev** package inside the requirement script (line 143 and 171).

so, adding such check for the dlpack package in cmake, and finding it, is sufficient?

**Comment by essamROCm** [comment]
@kiritigowda 
Added in this PR: https://github.com/ROCm/rocPyDecode/pull/109

**Comment by kiritigowda** [comment]
Can be merged with passing CI on #109

**Comment by essamROCm** [comment]
Fixed in https://github.com/ROCm/rocPyDecode/pull/109
